### ISSUE TITLE
wrong calculation

### ISSUE THREAD

**Issue by bubi-007** [emuflight/EmuFlight-Butter-Varient#14]
the constant is simply wrong.
have a look at the imu-f website or ask andrey

**Comment by Quick-Flash** [comment]
The constant for what is wrong? And how is it wrong?

**Comment by bubi-007** [comment]
on both side of the equal side should be the same.
if you reduce q then you need to ride the other factor.
or in other words, when lowering q to be handled better in the osd you should RISE the factor.
not further reduce it.
the cutoff frequency is in relation to the ratio of Q/R.

**Comment by Quick-Flash** [comment]
Well this looks like something that you would be best at fixing! You are the filtering pro.

**Comment by gretel** [comment]
@bubi-007 we would happily accept a pull request! closing for now..
