### ISSUE TITLE
Configurator dmg won't mount on some macs

### ISSUE THREAD

**Issue by F2GD** [emuflight/EmuFlight-Butter-Varient#23]
My Mac was originally on El capitain, I upgraded it to Mohave and the problem still persists. If you use the legacy file system it works fine, even though it is twice the size. 

Can you add a legacy_osx_emuflightconfigurator_v0_xx.dmg file for your releases

**Comment by loutwice** [comment]
should be corrected with new versions . @F2GD  let me know please

**Comment by gretel** [comment]
yes, issue is known, and we are getting close to release signed apps for osx.

**Comment by gretel** [comment]
https://github.com/emuflight/EmuConfigurator/issues/17
