### ISSUE TITLE
We need BLHELI32 esc start up tones

### ISSUE THREAD

**Issue by F2GD** [emuflight/EmuFlight-Butter-Varient#25]
We need this as a start up tone to copy and paste into blheli32 escs --> https://youtu.be/2WNrx2jq184?t=28

**Comment by F2GD** [comment]
But someone needs to make the notes for it. This is an issue of upmost importance. And if you remember the raceflight days, you will know that it can be done by the FC firmware too, but there is 0 point to do it that way

**Comment by gretel** [comment]
if somebody'd come up with an "emu tune" ...
