### ISSUE TITLE
Barometer & Magnetometer IIC 

### ISSUE THREAD

**Issue by InfernalFPV** [emuflight/EmuFlight-Butter-Varient#28]
I tried getting my barometer and mag working on my mamba I2c port but the CLI did not recognize any of the Baro/mag set codes is this something that will be implemented at some point? would be great to have a more accurate GPS rescue feature.

**Comment by gretel** [comment]
@InfernalFPV thanks for the report. chances are this will be supported with the next iteration of the gps features. please hang on. closing for now...
