### ISSUE TITLE
RC5: Filter Q & W adjustments via OSD do not align with limits in CLI

### ISSUE THREAD

**Issue by fxbisto** [emuflight/EmuFlight-Butter-Varient#7]
Managed to find this whilst troubleshooting a non-flier;
OSD settings still allow the Q to go too high but limit the W to 64.

```
# get filter
gyro_filter_q = 300  <---How has this saved!
Allowed range: 0 - 160
Default value: 30

gyro_filter_w = 64  <---Max OSD value
Allowed range: 3 - 512
Default value: 32
```

**Comment by Quick-Flash** [comment]
thanks for pointing this out. I'll look into this right now!

**Comment by Quick-Flash** [comment]
it appears that this is fixed in our newer testing versions!
should be out later this week!

**Comment by fxbisto** [comment]
Fantastic news! Unfortunately my charger went wrong but I will also test as soon as I can

**Comment by Quick-Flash** [comment]
new version will be out later this week. so once that comes out this should be fixed
